### ISSUE TITLE
Conseils a prendre ou à laisser

### ISSUE THREAD

**Issue by ZarTek-Creole** [tRyzoNeT/Eggdrop#1]
https://github.com/tRyzoNeT/Eggdrop/blob/c46dc630c8891546108453dbc1a97677228af372/preedb0t/preedb0t.v1.1.FRENCH.LiNUX.EGGDROP.TCL-RyZEN/addpre.tcl#L43

Je te conseille de faire un INSERT IGNORE et d'enlever le select avant tu va economiser une commande en SQL il sera que plus rapide le "set nix [...]" est également inutile 

le set addpre_(time) [clock seconds] au debut de ta proc pour avoir le temps de la commande plus proche de la realité que en fin parcours

les deuxiemes
```
 set chan [string tolower $chan]                                       
 if {[channel get $chan add]} {

```
aussi un peu inutile, je denigre pas ton travail, ce sont des conseils a tors ou a raisons voici ce que je te propose :

```

bind pub -|- !addpre ms:addpre
proc ms:addpre { nick uhost hand chan arg } {
    # Temps actuel
    set addpre_(time) [clock seconds]
    # chan en minuscule
    set chan [string tolower $chan]
    # Verification que le salon a le flag 'add' sinon on arette tout
    if {[channel get $chan add]} { return }
    # si aucun arguments n'ai fournis, on retourne l'aide et on arette tout
    if { $arg == "" } { putquick "privmsg $chan \002\0033(\00314ADDPRE\0033)\002\0037 Syntax * !addpre <nom.de.la.release> <section> <source>" }
    # Split sur les espace (je sais pas si utile?)
    set splitz [split $arg " "]
    # lindex au lieu de lrange
    set addpre_(release) [lindex $splitz 0]
   # un trim simple devrais surfir gain dune commande
    set addpre_(release) [string trim $addpre_(release) "\{\}"]
    # et tant que a faire reduison encore:
    set addpre_(section) [string trim [lrange $splitz 1] "\{\}"]
    set addpre_(source)  [string trim [lrange $splitz 2] "\{\}"]
    if { $addpre_(release) == "" } { putquick "privmsg $chan \002\0033(\00314ADDPRE\0033)\002\0037 Erreur * NOM de la RELEASE MANQUANTE"; return }
    if { $addpre_(section) == "" } { putquick "privmsg $chan \002\0033(\00314ADDPRE\0033)\002\0037 Erreur * SECTiON MANQUANTE"; return }
    if { $addpre_(source) == "" } { putquick "privmsg $chan \002\0033(\00314ADDPRE\0033)\002\0037 Erreur * SOURCE MANQUANTE"; return }
    # chargement/importation des variables dans ms:addpre
    global network prefix_ mysql_ db_ chan_
    set group [lindex [split $addpre_(release) -] end]
    # Un index unique sur SQL doit etre present sur la colonne $db_(rlsname) de la table $mysql_(table) pour utuiliser corectement le IGNORE sans ajouter en double
    mysqlexec $mysql_(handle) "INSERT IGNORE INTO $mysql_(table) ($db_(rlsname),$db_(grp),$db_(section),$db_(ctime),$db_(rls_addpre),$db_(rls_addpre_nick),$db_(rls_addpre_chan),$db_(rls_addpre_network),$db_(rls_addpre_source),$db_(rls_addold),$db_(rls_readd),$db_(rls_sitepre)) VALUES ( '$addpre_(release)' , '$group' , '$addpre_(section)' , '$addpre_(time)' , '1' , '$nick' , '$chan' , '$network' , '$addpre_(source)' , '0' , '0' , '0' )"
    # Pour les valeurs: 0 et 1, il doivent etremis comme valeur par defaut dans la structure de la tables et enlever ici pour reduire la longueur de la requette
    #putquick "privmsg $chan_(pred) (ADDPRE) $addpre_(release) - $addpre_(section)"
}

```

Voir #2

**Comment by tRyzoNeT** [comment]
jamais vu tes commentaire, mybad. woww si sa peu ameliorer la chose je regarde sa.
MERCi :)

**Comment by tRyzoNeT** [comment]
je vient de tester le code... malheureusement le eggdrop ne répond pas a la commande **!addpre** sur le channel, les flags sont pourtant bien ajouter.

**Comment by ZarTek-Creole** [comment]
En relisant le code je m'aperçois que je n'ai pas changer 2 lrange en lindex 
```
    set addpre_(section) [string trim [lrange $splitz 1] "\{\}"]
    set addpre_(source)  [string trim [lrange $splitz 2] "\{\}"]
``` 
deviens: 
```
    set addpre_(section) [string trim [lindex $splitz 1] "\{\}"]
    set addpre_(source)  [string trim [lindex $splitz 2] "\{\}"]
``` 

Et a vrai dire les string trim pour moi semble inutile ; les {} sont des listes; et ici ce sont des strings pas de raison d'avoir de {} et donc de 'string trim' sur { }

**Comment by tRyzoNeT** [comment]
hehehhee je n'est pas plus remarquer XD

je vais tester en supprimant ce qui semble inutile string et {}

**Comment by tRyzoNeT** [comment]
bind pub -|- !addpre ms:addpre
proc ms:addpre { nick uhost hand chan arg } {
 set addpre_(time) [clock seconds]
 set chan [string tolower $chan]
 if {[channel get $chan add]} { return }
 if { $arg == "" } { putquick "privmsg $chan \002\0033(\00314ADDPRE\0033)\002\0037 Syntax * !addpre <nom.de.la.release> <section> <source>" }
 set addpre_(release) [lindex $arg 0]
 set addpre_(section) [lindex $arg 1]
 set addpre_(source)  [lindex $arg 2]
 if { $addpre_(release) == "" } { putquick "privmsg $chan \002\0033(\00314ADDPRE\0033)\002\0037 Erreur * NOM de la RELEASE MANQUANTE"; return }
 if { $addpre_(section) == "" } { putquick "privmsg $chan \002\0033(\00314ADDPRE\0033)\002\0037 Erreur * SECTiON MANQUANTE"; return }
 if { $addpre_(source) == "" } { putquick "privmsg $chan \002\0033(\00314ADDPRE\0033)\002\0037 Erreur * SOURCE MANQUANTE"; return }
 global network prefix_ mysql_ db_ chan_
 set group [lindex [split $addpre_(release) -] end]
 mysqlexec $mysql_(handle) "INSERT IGNORE INTO $mysql_(table) ($db_(rlsname),$db_(grp),$db_(section),$db_(ctime),$db_(rls_addpre),$db_(rls_addpre_nick),$db_(rls_addpre_chan),$db_(rls_addpre_network),$db_(rls_addpre_source),$db_(rls_addold),$db_(rls_readd),$db_(rls_sitepre)) VALUES ( '$addpre_(release)' , '$group' , '$addpre_(section)' , '$addpre_(time)' , '1' , '$nick' , '$chan' , '$network' , '$addpre_(source)' , '0' , '0' , '0' )"
 #putquick "privmsg $chan_(pred) (ADDPRE) $addpre_(release) - $addpre_(section)"
}

**Comment by ZarTek-Creole** [comment]
Si cela ne fonctionne pas il doit encore avoir une erreur. je l'ai fais sans tester. Vous pouvez toujours faire apres `!addpre test test` un `.set ::errorInfo` ou un ".tcl return $::errorInfo"  dans votre party line pour qu'il vous affiche des informations sur la dernière erreur qu'il a rencontrer . si vous avez set ou/et tcl activé dans votre config.

les lindex semble bon, j'ai relu le code et fais ceci : 
```
bind pub -|- !addpre ms:addpre
proc ms:addpre { nick uhost hand chan arg } {
    set addpre_(time)   [clock seconds]
    set chan            [string tolower $chan]
    if { [channel get $chan add] } { 
        putlog "L'utilisateur ${nick} à tenté un !addpre sur ${chan}, mais le salon n'a pas les flags necesaire."
        return 
    }
    if { $arg == "" } { putquick "privmsg $chan \002\0033(\00314ADDPRE\0033)\002\0037 Syntax * !addpre <nom.de.la.release>" }
    set addpre_(release)    [lindex ${arg} 0]
    set addpre_(section)    [lindex ${arg} 1]
    set addpre_(source)     [lindex ${arg} 2]
    if { ${addpre_(release)} == "" } { putquick "privmsg ${chan} \002\0033(\00314ADDPRE\0033)\002\0037 Erreur * NOM de la RELEASE MANQUANTE"; return }
    if { ${addpre_(section)} == "" } { putquick "privmsg ${chan} \002\0033(\00314ADDPRE\0033)\002\0037 Erreur * SECTiON MANQUANTE"; return }
    if { ${addpre_(source)} == "" } { putquick "privmsg ${chan} \002\0033(\00314ADDPRE\0033)\002\0037 Erreur * SOURCE MANQUANTE"; return }
    global network prefix_ mysql_ db_ chan_
    set group               [lindex [split ${addpre_(release)} -] end]
    set SQL_INSERT          "INSERT IGNORE INTO $mysql_(table) ( "
    append SQL_INSERT          "`${db_(rlsname)}`, `${db_(grp)}`, `${db_(section)}`, `${db_(ctime)}`, `${db_(rls_addpre)}`, "
    append SQL_INSERT          "`${db_(rls_addpre_nick)}`, `${db_(rls_addpre_chan)}`, `${db_(rls_addpre_network)}`, "
    append SQL_INSERT          "`${db_(rls_addpre_source)}`, `${db_(rls_addold)}`, `${db_(rls_readd)}`, `${db_(rls_sitepre)}` "
    append SQL_INSERT       ") VALUES ( "
    append SQL_INSERT           "'${addpre_(release)}', '${group}', '${addpre_(section)}', '${addpre_(time)}','1', "
    append SQL_INSERT           "'${nick}', '${chan}', '${network}', "
    append SQL_INSERT           "'${addpre_(source)}', '0', '0', '0' "
    append SQL_INSERT       ");"
    mysqlexec ${mysql_(handle)} ${SQL_INSERT}
    if { [::mysql::insertid ${mysql_(handle)}] != ""} { putlog "La release ${addpre_(release)} à été ajouter par ${chan}/${nick}"}
}

```

**Comment by tRyzoNeT** [comment]
wow mygod quelqu'un qui connais le partyline 👍 

le resultat dit : L'utilisateur X à tenté un !addpre sur #chan le salon n'a pas les flags necesaire.

config.chan 
`channel set #chan +udef-flag-add`

**Comment by ZarTek-Creole** [comment]
Avez vous correctement mis `setudef flag add` en dehors de la proc pour le declarer?
et `.chanset #NomDuChan +add` pour l'activé ?

Note: 'add' me semble être une mauvaise idée de flag, qui pourrais être utiliser par un autre script pourquoi pas `msaddpre`, si vous le changer, n'oublier pas de changer la ligne : 
` if { [channel get ${chan} add] } { `

**Comment by tRyzoNeT** [comment]
`setudef flag add` oui est en dehors de la proc qui fonctionne avec le addpre actuel.
`.chanset #NomDuChan +add` est activé

il n'y a aucun autre scripts de charger sur le eggdrop pour qu'il y a un conflit mais bonne idée, je prend note de changer sa au cas ou dans le futur sa pourrais rentrée en conflit... donc pour revenir a nos mouton après avoir changer le flag par +msaddpre (merci encore) la même erreur ce poursuis **l'utilisateur X à tenté un !addpre sur #chan le salon n'a pas les flags necesaire.**

**Comment by ZarTek-Creole** [comment]
```
   if { [channel get ${chan} add] } { 
        putlog "L'utilisateur ${nick} à tenté un !addpre sur ${chan}, mais le salon n'a pas les flags necesaire."
        return 0;
    }
```
C'est logique, car là nous lui disons si le salon $chan a le flag add, alors affiche le putlog, et arête toi là.

ici, ont veux qu'il fasse l'inverse, qu'il affiche l'erreur et arête la , si le flag n'existe pas.
Il faut donc inverser avec un ! devant [ ... ]

`   if { ![channel get ${chan} add] } { `

**Comment by tRyzoNeT** [comment]
C'est logique certain :) ses toujours des petits détails que tu réalise par la suite.

**TESTER et FONCTiONNEL** 👍 

je vais modifier les autres tcl, coté rapidité wow avec une connexion toujours ouverte au mysql. 
La perfection `preedb0t v2.0` a venir...
@ZarTek-Creole  sérieux UN GROS MERCi

**Comment by ZarTek-Creole** [comment]
> je vais modifier les autres tcl, coté rapidité wow avec une connexion toujours ouverte au mysql. La perfection `preedb0t v2.0` a venir... @ZarTek-Creole sérieux UN GROS MERCi

De rien, je suis content de t'avoir aidé. ainsi que tes utilisateurs.

Je suis disponible sur irc.Extra-cool.fr en cas de nécessité. 

Bonne continuation
