### ISSUE TITLE
mySQLTCL ** windows x64

### ISSUE THREAD

**Issue by tRyzoNeT** [tRyzoNeT/Eggdrop#5]
Salut a tous, ou est-ce que je puis-je trouver mysql.tcl sur windows x64...

en ce moment il y a seulement la version x86 32bit qui n'est pas utile sur les système de nos jour.

http://www.xdobry.de/mysqltcl/windows.html

**Comment by ZarTek-Creole** [comment]
La compilation du code source pour une prise en charge sur un système 64 bits requiert un environnement de construction adapté. Le code en question est écrit en C et sert d'extension à Tcl. Si le code a été élaboré en tenant compte des spécificités d'un système 32 bits, il se peut qu'il ne fonctionne pas correctement lorsqu'il est compilé pour un système 64 bits, sans apporter quelques modifications.

Néanmoins, après avoir examiné le code source de `mysqltcl`, il ne semble pas y avoir de dépendances spécifiques à un système 32 bits. En théorie, cela signifie qu'il devrait être possible de compiler ce code sur un système 64 bits, à condition qu'il n'y ait pas de dépendances ou d'hypothèses non explicites.

Pour accomplir cela, vous aurez besoin d'un compilateur C 64 bits (comme gcc ou clang) ainsi que des fichiers de développement pour Tcl et la bibliothèque cliente MySQL. Voici les étapes de base :

1. Installez les fichiers de développement pour Tcl et la bibliothèque cliente MySQL. Ces fichiers incluent généralement des en-têtes et des bibliothèques qui sont nécessaires pour la compilation du code source.
2. Téléchargez le code source à partir du lien que vous avez fourni.
3. Exécutez le compilateur avec les options appropriées pour produire une DLL 64 bits. Cela nécessitera une connaissance des options de compilation spécifiques pour votre compilateur et de la manière dont la bibliothèque doit être construite.

Méthode 2 : Vous pouvez compiler le code source de `mysqltcl` en utilisant Cygwin et ainsi obtenir le fichier `.so` correspondant.

Cela est similaire à la compilation de l'eggdrop avec Cygwin pour Windows. Cygwin est une collection de logiciels libres et open source qui émule un environnement Unix sur Windows, vous permettant de compiler et d'exécuter des logiciels Unix-like directement sur votre machine Windows. Vous pouvez trouver plus d'informations sur l'installation de Cygwin ici :
- https://www.cygwin.com/
- https://github.com/code-warrior/installing-cygwin

Méthode 3 : Une autre option pourrait être d'utiliser le Sous-système Windows pour Linux (WSL2). C'est une solution qui pourrait s'avérer plus élégante. Avec WSL2, vous pouvez exécuter un environnement Linux directement sur Windows, sans avoir à configurer un dual-boot. Cela vous permettrait d'installer et d'utiliser des outils Linux natifs directement sur votre machine Windows. Si le code source de `mysqltcl` est plus facile à compiler dans un environnement Linux, l'utilisation de WSL2 pourrait être particulièrement avantageuse. En outre, WSL2 offre une intégration complète avec le système de fichiers Windows, ce qui pourrait faciliter le processus de compilation et d'installation.
